name: Terraform Dev Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'environments/dev/**'
      - 'modules/**'
      
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: AWS Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev
    env:
      TF_IN_AUTOMATION: true
      
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # AWS OIDC Authentication
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::292123551780:role/GitHubActionsOIDC-demo-role
          aws-region: ap-south-1

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.2

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -lock-timeout=10m -no-color -var-file="dev.tfvars"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -input=false -lock-timeout=10m -no-color -var-file="dev.tfvars" -auto-approve